# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.2'

# Auth
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

# CORS
gem 'rack-cors'

# Background jobs
gem 'sidekiq'

# Image processing (ActiveStorage)
gem 'image_processing', '~> 1.2'

# HTTP client (for Perenual API)
gem 'faraday'

# Performance
gem 'bootsnap', require: false

gem 'tzinfo-data', platforms: [:windows, :jruby]

group :development, :test do
  gem 'debug', platforms: [:mri, :windows], require: 'debug/prelude'
  gem 'faker'
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'annotaterb'
end
